# Generated by Django 2.2 on 2021-05-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0002_auto_20210503_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photos',
            field=models.ManyToManyField(related_name='photo_comments', to='Newapp.Photo'),
        ),
    ]
